### ISSUE TITLE
Slider does not render on Safari (MacOS and iOS including companion app)

### ISSUE THREAD

**Issue by ksendor** [mattieha/slider-button-card#10]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** v1.1.0

**Last working release (if known):** N/A

**Browser and Operating System:** Safari / MacOS & iOS

**Description of problem:** Slider (any type like solid, gradient, striped etc.) does not show at all on Safari on MacOS and iOS (including Home Assistant companion app for iOS). Tested with many different themes. Same config (shown below) renders correctly (slider is visible) on Chrome. Additionally on iOS there is visible bar that is the handle of slider (also visible in visual edit mode on Safari on MacOS). 

![slider-button-card](https://user-images.githubusercontent.com/3611824/121756665-32b1ca00-cb1b-11eb-9fa2-36c5f9467358.jpg)

```yaml
type: custom:slider-button-card
entity: switch.living_room_neon
name: Neon
slider:
  percentage: false
  direction: left-right
  background: striped
  use_state_color: false
  use_percentage_bg_opacity: false
  show_track: false
  force_square: true
show_name: true
show_state: false
icon:
  show: true
  use_state_color: false
  rotate: false
  tap_action:
    action: more-info
action_button:
  mode: toggle
  show_spinner: true
```

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**
