### ISSUE TITLE
Lock mode error

### ISSUE THREAD

**Issue by WhistleMaster** [mattieha/slider-button-card#125]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 1.11.0-beta

**Last working release (if known):** n/a

**Browser and Operating System:**
Firefox 91.0.2 / Mac OS X

**Description of problem:**
When used with lock mode, card cannot be unlocked or used.

**Javascript errors shown in the web inspector (if applicable):**

```
Uncaught TypeError: this.card is null
    unlockCard https://ha/hacsfiles/slider-button-card.js:610
    handleLockClick https://ha/hacsfiles/slider-button-card.js:610
    handleEvent https://ha/hacsfiles/slider-button-card.js:83
    __boundHandleEvent https://ha/hacsfiles/slider-button-card.js:83
slider-button-card.js:610:531
```

**Additional information:**
```
type: custom:slider-button-card
entity: cover.mycover
slider:
  direction: top-bottom
  background: striped
  show_track: false
  force_square: false
  lock:
    enabled: true
    duration: 5
icon:
  show: true
  tap_action:
    action: more-info
  icon: ''
  use_state_color: false
action_button:
  tap_action:
    action: toggle
  mode: custom
  icon: mdi:swap-vertical
  show: true
  show_spinner: false
compact: false
```
