### ISSUE TITLE
Failed to call service media_player/volume_mute. must contain at least one of entity_id, device_id, area_id.

### ISSUE THREAD

**Issue by pete-leese** [mattieha/slider-button-card#139]
I am trying to create a volume slider, but with a call service to mute to speakers, I've setup a tap action on the icon to call a service media_player.volume_mute, but doesnt appear to be working, instead I receive the following error:

**Failed to call service media_player/volume_mute. must contain at least one of entity_id, device_id, area_id.**

This is despite the configuration containing an entity ID. 

Please find below example configuration used to validate bug.

```
type: custom:slider-button-card
entity: media_player.garden_office
slider:
  direction: left-right
  background: gradient
  use_state_color: true
  use_percentage_bg_opacity: true
  show_track: false
  toggle_on_click: false
  force_square: false
show_name: true
show_state: true
compact: true
icon:
  show: true
  use_state_color: true
  icon: mdi:volume-high
  tap_action:
    action: call-service
    service: media_player.volume_mute
    service_data:
      is_volume_muted: true
    target:
      entity_id:
        - media_player.garden_office
action_button:
  mode: custom
  icon: mdi:power
  show: true
  show_spinner: true
  tap_action:
    action: toggle
name: Ceiling Speaker Volume
```
