### ISSUE TITLE
Action call service: input_boolean:toogle doesn’t work

### ISSUE THREAD

**Issue by kwithus** [mattieha/slider-button-card#199]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

I am trying to implement a call service action, however I do get an error

`type: custom:slider-button-card
slider:
  direction: top-bottom
  background: solid
  use_state_color: false
  use_percentage_bg_opacity: true
  toggle_on_click: false
  show_track: false
  force_square: false
  invert: true
show_name: true
show_state: true
compact: false
icon:
  show: true
  use_state_color: true
  tap_action:
    action: call-service
    service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.rollo_automation_wohnzimmer
  icon: ''
action_button:
  mode: custom
  icon: mdi:power
  show: true
  show_spinner: true
  tap_action:
    action: call-service
    service: input_boolean.toggle
    data: {}
    target:
      entity_id: input_boolean.rollo_automation_wohnzimmer
entity: cover.rollos_wohnzimmer
name: WZ Alle
`
![B3F1839C-D5B6-4C7E-AD49-5C0A0A3EC942](https://user-images.githubusercontent.com/20025320/174874375-f5166937-2415-4c3a-b59a-19ea39c0033e.jpeg)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by harryinet** [comment]
Same at my dashboard. Can´t i trigger an automation?

**Comment by davetoland** [comment]
You need to add an entity_id to the service data, something like this:

```
action_button:
  mode: custom
  show: true
  tap_action:
    action: call-service
    service: input_boolean.toggle
    service_data:
      entity_id: input_boolean.hvactoggle
      target_id: climate.living_room
```
