### ISSUE TITLE
Lovelace example, please

### ISSUE THREAD

**Issue by seventhsite** [mattieha/slider-button-card#22]
Hello!
Can you give me an example of card code with a maximum of options, please.

**Comment by alexisteleco** [comment]
When the component is installed, it ships with a (not working because lacking of entity_id) example. It is:

```yaml
type: custom:slider-button-card
entity: '<put here your entity_id>'
slider:
  percentage: true
  direction: left-right
  background: gradient
  use_state_color: false
  use_percentage_bg_opacity: false
  show_track: false
  force_square: false
show_name: true
show_state: true
icon:
  show: true
  use_state_color: true
  rotate: false
  tap_action:
    action: more-info
action_button:
  mode: toggle
  icon: mdi:power
  show: true
  show_spinner: true
  tap_action:
    action: toggle
```

**Comment by seventhsite** [comment]
> When the component is installed, it ships with a (not working because lacking of entity_id) example. It is:

Thank you! 
I can't change icon to another one. This construction don't work:

```
          - type: custom:slider-button-card
            entity: light.light_room_lamp
            icon: mdi:floor-light
            use_state_color: true
            name: Лампа
```
And this too:

```
              icon:
                show: true
                use_state_color: true
                rotate: false
                tap_action:
                  action: more-info
              action_button:
                mode: toggle
                icon: floor-light
                show: true
                show_spinner: true
                tap_action:
                  action: toggle
```

**Comment by KairuByte** [comment]
You need to pay attention to indentation, as well as expected values.

Your first example is not supplying an object as expected, you're supplying a string. 


Your second example is supplying the toggle object properly, but the icon string is missing "mdi:"

Use the UI card tool to get a feeling for what the values should be, or read through the docs, and you'll have a much better time with this.

**Comment by seventhsite** [comment]
Thank you!
Looks like I don't understand expected values :(

> Your second example is supplying the toggle object properly, but the icon string is missing "mdi:"

Oops. So, I use it with mdi and also nothing new.
Copy paste from example:

```
            - type: custom:slider-button-card
              entity: light.light_hall_l1
              name: Коридор
              icon:
                show: true
                use_state_color: true
                rotate: false
                tap_action:
                  action: more-info
              action_button:
                mode: toggle
                icon: mdi:power
                show: true
                show_spinner: true
                tap_action:
                  action: toggle
```
give me this with default icon

[](https://s1.hostingkartinok.com/uploads/images/2021/06/26962ba8eaf711d50cbcd52eeba2a169.png)

**Comment by KairuByte** [comment]
Mode should be custom in that example, sorry was on mobile and missed it. Toggle overrides pretty much everything else for the action button.

**Comment by seventhsite** [comment]
> Mode should be custom in that example, sorry was on mobile and missed it. Toggle overrides pretty much everything else for the action button.

Yes, it work!

```
              action_button:
                mode: custom
                icon: mdi:power
```

Anyway, looks like there is a lot of code for only icon change. What code will be enough for slider with default options and only new icon?

**Comment by seventhsite** [comment]
Experiments give me this:

```
          - type: custom:slider-button-card
            entity: light.light_room_lamp
            name: Лампа
            icon:
              show: true
              use_state_color: true
              icon: mdi:floor-lamp-dual
            action_button:
              mode: custom
              icon: mdi:power
              show_spinner: true
              tap_action:
                action: toggle
```
