### ISSUE TITLE
input_number in v1.12.0 is not working

### ISSUE THREAD

**Issue by danielbrunt57** [mattieha/slider-button-card#227]
**Checklist:**
- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v1.12.0
![image](https://github.com/mattieha/slider-button-card/assets/49846893/15ca9da4-dda6-4b22-9568-d7ad0791dc0e)

**Last working release (if known):**
n/a

**Browser and Operating System:**
MS Edge / Windows 11 Professional

**Description of problem:**
![image](https://github.com/mattieha/slider-button-card/assets/49846893/754c269e-bb4d-40a5-b543-da63ace5f6ec)

**Additional information:**
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: cover.bedroom_blind
        type: custom:multiple-entity-row
        name: Bedroom
        show_state: false
        entities:
          - entity: input_number.bedroom_blind
            name: Preset
          - entity: sensor.bedroom_blind_battery
            name: Battery
          - entity: sensor.bedroom_blind_battery
            name: false
            icon: true
    show_header_toggle: false
    state_color: false
    card_mod:
      class: inline-card
  - type: custom:slider-button-card
    slider:
      direction: bottom-top
      background: gradient
      attribute: tilt
      use_state_color: true
      use_percentage_bg_opacity: true
      toggle_on_click: false
      show_track: true
      force_square: false
      invert: true
    action_button:
      mode: toggle
      show: false
    icon:
      show: false
    entity: cover.bedroom_blind
    show_state: true
    compact: tr
    show_name: false
    name: Bedroom
  - type: custom:slider-button-card
    slider:
      direction: left-right
      background: gradient
      use_state_color: false
      use_percentage_bg_opacity: false
      toggle_on_click: false
      show_track: false
      force_square: false
      invert: false
    icon:
      show: false
    entity: input_number.bedroom_blind
    show_state: true
    compact: true
    show_name: false
    name: Bedroom
```
