### ISSUE TITLE
Can't start Timer (must contain entity)

### ISSUE THREAD

**Issue by boehser-enkel** [mattieha/slider-button-card#234]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
2024.4
**Last working release (if known):**
-
**Browser and Operating System:**
any

any
**Description of problem:**

Timer does not start (must contain entity)

```
type: custom:slider-button-card
entity: input_number.druckertimer_dauer
slider:
  direction: left-right
  background: gradient
  use_state_color: false
  use_percentage_bg_opacity: false
  show_track: false
  toggle_on_click: false
  force_square: false
show_name: true
show_state: true
compact: false
icon:
  show: true
  use_state_color: true
  tap_action:
    action: more-info
  icon: ''
action_button:
  mode: custom
  show: true
  show_spinner: true
  tap_action:
    action: call-service
    service: timer.start
    target:
      entity_id:
        - timer.drucker
    data: {}
show_attribute: false



```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
