### ISSUE TITLE
Request - Lock Slider Button to prevent accidental interactions

### ISSUE THREAD

**Issue by jonathanathe** [mattieha/slider-button-card#72]
**Is your feature request related to a problem? Please describe.**

When using the "Slider Button Card" together with the "[Swipe Nav](https://github.com/maykar/lovelace-swipe-navigation)" it happens quite often that when I want to turn to the next page I accidentally interrupt the light buttons by swiping and turning them on or off. 

**Describe the solution you'd like**
It would be great to integrate the function of locking the button and having to press first and then interact with the slider button.

Example:

[button-card #lock](https://github.com/custom-cards/button-card#lock)

Finally, I would like to thank you for the work you are doing, which I love. And excuse me if the text is not totally well written as I use the translator.

**Comment by mattieha** [comment]
Thanks for your feedback.
I like the idea for a lock mode, I'll add it  to the roadmap.

**Comment by mattieha** [comment]
@jonathanathe I've added this feature in a beta release: v.1.11.0-beta could you test this if you got time?

**Comment by jonathanathe** [comment]
Hello @mattieha ! Can you help me to know how to integrate it remove the old file "slider-button-card.js" and put the new file and restart, I do not see in the interface that I get option can you tell me how to do it? Thank you. Regards.

**Comment by jonathanathe** [comment]
@mattieha It works perfectly, an addition that will help a lot with accidental touches. Thank you for your research time and work!

**Comment by DomiStyle** [comment]
I updated to v.1.11.0-beta because I had the same issue but it seems like I can't figure out how to unlock the sliders? I tried double tapping and holding but it won't unlock.

This is my config:

```
type: grid
cards:
  - type: custom:slider-button-card
    slider:
      direction: left-right
      background: gradient
      use_state_color: true
      use_percentage_bg_opacity: false
      show_track: false
      toggle_on_click: false
      force_square: false
      lock:
        enabled: true
        duration: 5
    show_name: true
    show_state: false
    compact: false
    icon:
      show: true
      use_state_color: true
      tap_action:
        action: more-info
      icon: ''
    action_button:
      mode: toggle
      icon: mdi:power
      show: false
      show_spinner: true
      tap_action:
        action: toggle
    entity: light.bedroom
  - type: custom:slider-button-card
    slider:
      direction: left-right
      background: gradient
      use_state_color: true
      use_percentage_bg_opacity: false
      show_track: false
      toggle_on_click: false
      force_square: false
      lock:
        enabled: true
        duration: 1
    show_name: true
    show_state: false
    compact: true
    icon:
      show: true
      use_state_color: true
      tap_action:
        action: more-info
      icon: ''
    action_button:
      mode: toggle
      icon: mdi:power
      show: false
      show_spinner: true
      tap_action:
        action: toggle
    entity: light.bedroom_main
columns: 1
square: false

```
