### ISSUE TITLE
Where are the examples?

### ISSUE THREAD

**Issue by AnthonMS** [mattieha/slider-button-card#77]
Where are the yaml examples? When I try to use it like:

```yaml
  - type: custom:slider-button-card
    entity: light.bedroom_spots
    name: Bedroom
    icon: mdi:desk-lamp
    action_button:
      mode: toggle
      icon: mdi:power
```

The action button doesnt change from the toggle switch and the icon doesnt change from the default lightbulb??

**Comment by AnthonMS** [comment]
Okay, I played around with it some more. And it just didn't make sense I had to do icon: icon: but now I know.

But I have found a bug really quickly.

This config works:

```yaml
  - type: custom:slider-button-card
    entity: light.grono_lamp_office
    name: Desk Lamp
    icon: 
      icon: mdi:desk-lamp
    action_button:
      icon: mdi:power
      tap_action: 
        action: toggle
```

But as soon as I try to make it look like you have in your examples by setting the slider config. It just acts as a button. 

```yaml
  - type: custom:slider-button-card
    entity: light.grono_lamp_office
    name: Desk Lamp
    icon: 
      icon: mdi:desk-lamp
    action_button:
      icon: mdi:power
      tap_action: 
        action: toggle
    slider:
      background: solid
    style: |
      ha-card {
        border-radius: 10px;
      }
```

This makes it incredibly hard to see the percentage when using it for a cover. Since the white/black stripes as background and white text...
